# ref: https://github.com/pre-commit/pre-commit/issues/1930
# default_language_version:
#   ruby: 3.2.1
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=crlf]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.49.1
    hooks:
      - id: markdownlint
        exclude: ^CHANGELOG\.md$
        args:
          - "-c"
          - ".github/linters/.markdown-lint.yml"

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.2
    hooks:
      - id: actionlint

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.29.0
    hooks:
      # Run the linter.
      - id: zizmor
        args:
          - "-c"
          - ".github/linters/zizmor.yaml"

  - repo: https://github.com/crate-ci/typos
    rev: v1.24.6
    hooks:
      - id: typos
        exclude: (.*\.yaml|^CHANGELOG.md$)

  # Local hooks
  - repo: local
    hooks:
      - id: prettier-format
        name: Prettier format
        entry: bun x prettier --write "**/*.md"
        language: system
        pass_filenames: false

      - id: powershell-format-check
        name: PowerShell format check
        entry: pwsh -NoProfile -ExecutionPolicy Bypass -File ./tools/format.ps1 -Check
        language: system
        pass_filenames: false

      - id: powershell-format
        name: PowerShell format
        entry: pwsh -NoProfile -ExecutionPolicy Bypass -File ./tools/format.ps1
        language: system
        pass_filenames: false

      - id: psscriptanalyzer
        name: PSScriptAnalyzer
        entry: pwsh -NoProfile -ExecutionPolicy Bypass -File ./tools/lint.ps1
        language: system
        pass_filenames: false
