name: "Release"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]

permissions: read-all

defaults:
  run:
    shell: pwsh

concurrency:
  group: "${{ github.workflow }}@${{ github.ref }}"

jobs:
  release:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ANC_GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6
        id: semantic
        with:
          semantic_version: 24
          branches: |
            [
              'main',
              'next'
            ]
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/exec@7.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@8.0.0
